# Polyglot Container Image — Generated by CPM (Universal Package Platform)
FROM python:3.12-slim

# Install system dependencies, Node.js, and Rust toolchain
RUN apt-get update && apt-get install -y \
    curl build-essential pkg-config libssl-dev git \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

# Copy project files
COPY . .

# Build Rust CPM release binary
RUN cargo build --release

# Install all dependencies across detected ecosystems concurrently
RUN ./target/release/cpm install --parallel

EXPOSE 3000

# Default entry point
CMD ["node", "examples/rfp_proposal_platform/server.js"]
