ecosystems = [
    "uv",
    "pnpm",
    "cargo",
]

[project]
name = "my_first_polyglot_app"
version = "0.1.0"
primary_language = "python"

[foreign_dependencies]
"cargo:requests" = "latest"
"cargo:serde" = "latest"
"npm:express" = "^4.19.2"
"pip:requests" = "latest"

[transports]
default_tier = "rpc"
