/// # `cpm dockerfile` CLI Subcommand — Polyglot Dockerfile Generator
///
/// Inspects workspace active ecosystems and generates an optimized, multi-stage
/// polyglot Dockerfile tailored for containerized production deployment.

use crate::acquisition::{AdapterRegistry, DetectionEngine};
use colored::Colorize;
use std::path::Path;

/// Auto-generate polyglot Dockerfile.
pub fn execute_dockerfile(path: &Path, out_file: Option<&str>) -> anyhow::Result<()> {
    println!();
    println!("  {}", "╭──────────────────────────────────────────────────────╮".cyan());
    println!("  {}  🐳 {}{}",
        "│".cyan(),
        "CPM Polyglot Dockerfile Auto-Generator".bold().white(),
        "          │".cyan(),
    );
    println!("  {}", "╰──────────────────────────────────────────────────────╯".cyan());
    println!();

    let registry = AdapterRegistry::new();
    let engine = DetectionEngine::new(registry);
    let result = engine.detect_dir(path);

    let target_name = out_file.unwrap_or("Dockerfile");
    let target_path = path.join(target_name);

    println!("  ▶ Detecting ecosystems for container optimization...");
    for eco in &result.detected_ecosystems {
        println!("    ✔ Including {} ({})", eco.display_name.bold(), eco.language.dimmed());
    }
    println!();

    let dockerfile_content = format!(r#"# Polyglot Container Image — Generated by CPM (Universal Package Platform)
FROM python:3.12-slim

# Install system dependencies, Node.js, and Rust toolchain
RUN apt-get update && apt-get install -y \
    curl build-essential pkg-config libssl-dev git \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.cargo/bin:${{PATH}}"

WORKDIR /app

# Copy project files
COPY . .

# Build Rust CPM release binary
RUN cargo build --release

# Install all dependencies across detected ecosystems concurrently
RUN ./target/release/cpm install --parallel

EXPOSE 3000

# Default entry point
CMD ["node", "examples/rfp_proposal_platform/server.js"]
"#);

    std::fs::write(&target_path, dockerfile_content)?;

    println!("  {} Polyglot Dockerfile created at {}", "✔".green(), target_name.bold().yellow());
    println!("  {} Build with: {}", "ℹ".blue(), format!("docker build -t cpm-app .").cyan());
    println!();

    Ok(())
}
